language: cpp
compiler:
    - gcc
before_install:
    # disable rvm, use system Ruby
    - rvm reset
    - wget https://raw.githubusercontent.com/yast/yast-devtools/master/travis-tools/travis_setup.sh
    - sh ./travis_setup.sh -p "yast2 yast2-storage" -g "rake yast-rake yard rspec:2.14.1"
script:
    - yardoc
    - rake test:unit
    - sudo rake install

